---
- name: Deploy Docker Web App
  hosts: web-servers
  become: yes
  gather_facts: yes

  tasks:
    - name: Login to Docker Hub
      shell: "echo '{{ my_docker_password }}' | docker login --username abdrak --password-stdin"

    - name: Pull Docker image from Hub
      shell: "docker pull abdrak/docker-test:latest"

    - name: Run Container
      docker_container:
        name: "test-{{ ansible_date_time.epoch }}"
        image: abdrak/docker-test:latest
        state: started
        published_ports:
          - "{{ 30000 | range(31000) | random }}:80"
