---
- hosts: all
  become: yes
  tasks:
    - name: Konteynerleri Listele
      shell: "docker ps --format 'table {{.ID}}\t{{.Names}}\t{{.Status}}\t{{.Ports}}' --filter name=test-app-"
      register: docker_res
    - debug: msg="{{ docker_res.stdout_lines }}"
