---
---
- name: Get Docker Containers Status
  hosts: all
  become: yes
  tasks:
    - name: Tüm test konteynerlerini listele (Çalışan ve Duranlar)
      shell: "docker ps -a --format 'table {% raw %}{{.ID}}\t{{.Names}}\t{{.Status}}\t{{.Ports}}{% endraw %}' --filter name=test-app-"
      register: docker_res

    - name: Sonucu AWX Loglarına Yazdır
      debug:
        msg: "{{ docker_res.stdout_lines }}"
